---
title: First post!
author: Emma McLarnon
date: '2018-04-14'
slug: first-post
categories:
  - gardening
  - edibles
tags: 
  - blogdown
  - gardening
  - edibles
  - raspberry pi
---

Hello and welcome to my first post!  I am very pleased to have come this far.  I have to admit, I'm not really sure I know what I'm doing with blogdown!  **Disclaimer alert** if any links on the site don't work, please leave me a comment and I'll try to fix them.

Today I'm planning on deploying the site using Netlify because that's what I've read on a couple of other blogs (https://alison.rbind.io/post/up-and-running-with-blogdown/). It is supposed to be relatively easy for deployment and site maintenance. 

After that, I need to plant the seeds I've been germinating inside for a week now.  These include:

| Seed | Variety |
| :--: | :------:|
|Dwarf French bean| Purple queen|
|French bean| Ferrari|
|Chives| |
|Garlic chives|
|Cape gooseberry| |
|Mange tout| Shiraz|
|Basil| Opal|
|Chilli|Patio - firework|
|Pea| Greenshaft|
|Courgette| yellow and Black beauty|
|Sweetcorn| |
|Cucumber| Lemon, Crystal and Marketmore 76|
|Soybean| Elena|
|Cucamelon| |
|Squash| Trombincino, Patty Pan and Papaya|
|Tomatillo| Verde|

I will store these in the greenhouse until the weather gets a little warmer, which it is actually due to in the next week (FINALLY!).

My last job of this weekend is to set up my DH22 (https://www.adafruit.com/product/385) in the greenhouse using my Raspberry Pi - this is a temperature and humidity sensor (bought from eBay for £4.20).  I will be making a database using MySQL and storing the temperature and humidity data there (links to the tutorial will be in the next post).  I will also upload the data onto the site and attempt (in the future) to hook up a live stream, but I need to get better with coding before I can do that.  For now, I will settle with a summary of the data.  I intend to collect it hourly because I'm going to attach a battery pack to the Pi, so I need to see how long it lasts before it runs out of juice... more to come when I've set it all up!

For now, I will end my first post and hopefully be back regularly with updates.




