---
title: Allotment update
author: Emma McLarnon
date: '2019-05-29'
slug: allotment-update
type: post
---


Okay – so it’s been ages and there’s a lot to update on.

### Allotment

Things are growing pretty well. Growing the plot at the moment are:
-	Purple rain potatoes
-	Pink fir apple potatoes
-	Maris piper potatoes
-	Broad beans (lots of them, clearly I was very eager with the sowing of them)
-	Peas (including shiraz mange tout and a few other varieties)
-	Squashes/ courgettes 
-	Sweet corn (though it’s looking quite sad)
-	Pak choi
-	Kohl rabi
-	Radishes
-	Beetroot
-	Romanesco cauliflower 
-	Brussel sprouts
-	Onions
-	Very dead garlic that didn’t grow very well
-	Leeks
-	Tigeralla tomato plants
-	Strawberries
-	Dwarf French beans and runner beans

All in all, everything is growing fairly well.  The rain started last week and someone forgot to turn it off, because the weather has been quite wet; though it saves me from watering the plants, so it’s silver lining.  The flea beetles are horrendous.  They are ruining my cool radishes.  I’ve been growing the Peter rabbit ones (long scarlett), French breakfast and white icicle ones; but the root maggots are abundant.  They also bolted with the sunny weather.  I’ve decided that I’m not going to bother with any more of the root vegetables because they are too much hassle and very little reward.  I may grow them in the greenhouse in buckets instead. 

The asparagus has been awesome, we had an amazing crop from it.  I’ve now let it grow and it is as tall as me! I am getting asparagus beetles which are annoying, I feel bad squishing them, but they will ruin the amazing bed that’s there.  They have to go.

Despite my terrible sizing troubles with the potatoes, they have appeared above ground.  I earthed them up so will keep doing this, though it’s quite difficult because I’ve put them in sort of wonky.  Plus, the odd potatoes from last year keep appearing in random patches as well.  
The onions are looking very good, they got off to a slow start, but look really big.  Not sure when to harvest them.  The garlic on the other hand has been a disaster.  It’s gone all yellow and basically died.  There are a few that look okay, but they also probably haven’t divided into cloves.  That is the last time I will put my efforts into garlic!

I trialled out putting a tomato plant in the ground to see how it fares, it’s doing good.  It’s the tigerella variety, so should look lovely.  The plot gets great sunshine, so I’m hoping that they will ripen if the temperatures would get warmer! The plant has little flower buds, so fingers crossed tomatoes will appear.

#### Home

The rhubarb plants I’ve put in the raised beds look good and the over-wintered Swiss chard is huge! The onions in the raised beds look fairly small compared to the allotment ones – not sure why they are so tiny.  They also keep falling over, I assume because they are quite top heavy.  
I’ve moved the chillies, cucumbers and tomatoes outside because they were getting a bit too hot in the greenhouse when the sun was on, but it’s also quite shaded there until about 2/3pm.  I thought putting them in fuller sun would be better for them.  The black Russian tomatoes have started to flower and they are quite big looking, so hopefully I’ll get a decent crop from them too.


One of my hazelnut trees hasn’t come out of hibernation, I’m not sure if it’s just dead – I keep scratching the bark and it’s green underneath in some areas so I’m not sure what it’s doing.  The other one looks good though.

#### Conclusions

I should be harvesting the onions and maybe some potatoes at the end of June.  I have been photographing progress, but I’m too lazy to put photos on now.
Until next time.
